# Task 2: Start by generating several files of different lengths (one of them very short, shorter than 128 bits),
# another at least 1MB. These can be generated by programs or manually created. Then, write a program to encrypt
# them using AES, with 128 and 256 bit keys. This key should be generated randomly, using a cryptographically secure
# random number generator.  Determine how many times you can encrypt and decrypt a particular file in a second. Make
# a calculation to determine what size of file you could decrypt in one second with various settings.

def encrypt_decrypt_128():
    print("key 128")


def encrypt_decrypt_256():
    print("Key 256")
